package example;

public class WhileLoopExample {

	public static void main(String[] args) {
		
		int i = 10;
		while(i>1) {
			System.out.println(i);
			i--;
		}
		
		//Iterating an array using while loop
		int arr[] = {2,11,45,9};
		
		int j = 0;
		while(j < 4) {
			System.out.println(arr[j]);
			j++;
		}

	}
	
	//Develop a game to guess the number which generated by the system randomly
	/*
	 * 1. Generate a random between 1 and 100 for the user to guess.
	 * 2. Display a prompt or a line of text asking the user to guess a number in that range.
	 * 3. Accept the user's guess as input.
	 * 4. Compare the user's guess to the computers number to see if the guess is too high,
	 *  too low, or correct
	 * 5. Display a message and number on the screen.
	 * 6. Prompt the user to guess another number until they guess correctly.
	 * 7. Ask the user if they'd like to play again.
	 *  
	*/
}
